# Generated by Django 6.0.4 on 2026-05-05 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoIot',
            fields=[
                ('id_dispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=50, unique=True)),
                ('modelo', models.CharField(max_length=80)),
                ('firmware_version', models.CharField(max_length=50)),
                ('ip_actual', models.GenericIPAddressField()),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dispositivo_iot',
            },
        ),
        migrations.CreateModel(
            name='EstadoAmbiental',
            fields=[
                ('id_estado_ambiental', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('nivel', models.CharField(max_length=20)),
                ('color_referencia', models.CharField(max_length=30)),
                ('prioridad', models.IntegerField()),
            ],
            options={
                'db_table': 'estado_ambiental',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('idRecursos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('url_backend', models.CharField(blank=True, max_length=45, null=True)),
                ('url_frontend', models.CharField(blank=True, max_length=45, null=True)),
                ('path', models.CharField(max_length=45)),
                ('icono', models.CharField(blank=True, max_length=45, null=True)),
                ('orden', models.CharField(max_length=45)),
                ('recurso_padre', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(default='activo', max_length=45)),
            ],
            options={
                'db_table': 'recurso',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('estado', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='TipoVariable',
            fields=[
                ('id_tipo_variable', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('simbolo', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
            ],
            options={
                'db_table': 'tipo_variable',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuarios', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='ZonaMonitoreo',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'zona_monitoreo',
            },
        ),
        migrations.CreateModel(
            name='ComandoRemoto',
            fields=[
                ('id_comando', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_comando', models.CharField(max_length=20)),
                ('payload', models.JSONField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_dispositivo', models.ForeignKey(db_column='id_dispositivo', on_delete=django.db.models.deletion.CASCADE, to='core.dispositivoiot')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'db_table': 'comando_remoto',
            },
        ),
        migrations.CreateModel(
            name='Buzzer',
            fields=[
                ('id_buzzer', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(default='APAGADO', max_length=20)),
                ('id_dispositivo', models.ForeignKey(db_column='id_dispositivo', on_delete=django.db.models.deletion.CASCADE, to='core.dispositivoiot')),
            ],
            options={
                'db_table': 'buzzer',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('id_dispositivo', models.ForeignKey(db_column='id_dispositivo', on_delete=django.db.models.deletion.CASCADE, to='core.dispositivoiot')),
            ],
            options={
                'db_table': 'alerta',
            },
        ),
        migrations.CreateModel(
            name='EstadoBuzzer',
            fields=[
                ('id_estado_buzzer', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
                ('motivo_variacion', models.CharField(blank=True, max_length=255, null=True)),
                ('activado_por', models.CharField(max_length=50)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('id_alerta', models.ForeignKey(db_column='id_alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.alerta')),
                ('id_buzzer', models.ForeignKey(db_column='id_buzzer', on_delete=django.db.models.deletion.CASCADE, to='core.buzzer')),
            ],
            options={
                'db_table': 'estado_buzzer',
            },
        ),
        migrations.CreateModel(
            name='LecturaSensor',
            fields=[
                ('id_lectura', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('id_dispositivo', models.ForeignKey(db_column='id_dispositivo', on_delete=django.db.models.deletion.CASCADE, to='core.dispositivoiot')),
            ],
            options={
                'db_table': 'lectura_sensor',
            },
        ),
        migrations.AddField(
            model_name='alerta',
            name='id_lectura',
            field=models.ForeignKey(db_column='id_lectura', on_delete=django.db.models.deletion.CASCADE, to='core.lecturasensor'),
        ),
        migrations.CreateModel(
            name='RespuestaComando',
            fields=[
                ('id_respuesta', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_respuesta', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('exitoso', models.BooleanField(default=True)),
                ('respuesta_json', models.JSONField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('id_comando', models.ForeignKey(db_column='id_comando', on_delete=django.db.models.deletion.CASCADE, to='core.comandoremoto')),
            ],
            options={
                'db_table': 'respuesta_comando',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=80)),
                ('pin_conexion', models.CharField(max_length=20)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('fecha_instalacion', models.DateField()),
                ('id_dispositivo', models.ForeignKey(db_column='id_dispositivo', on_delete=django.db.models.deletion.CASCADE, to='core.dispositivoiot')),
                ('id_tipo_variable', models.ForeignKey(db_column='id_tipo_variable', on_delete=django.db.models.deletion.CASCADE, to='core.tipovariable')),
            ],
            options={
                'db_table': 'sensor',
            },
        ),
        migrations.AddField(
            model_name='lecturasensor',
            name='id_sensor',
            field=models.ForeignKey(db_column='id_sensor', on_delete=django.db.models.deletion.CASCADE, to='core.sensor'),
        ),
        migrations.AddField(
            model_name='lecturasensor',
            name='id_tipo_variable',
            field=models.ForeignKey(db_column='id_tipo_variable', on_delete=django.db.models.deletion.CASCADE, to='core.tipovariable'),
        ),
        migrations.CreateModel(
            name='UmbralAlerta',
            fields=[
                ('id_umbral', models.AutoField(primary_key=True, serialize=False)),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('id_estado_ambiental', models.ForeignKey(db_column='id_estado_ambiental', on_delete=django.db.models.deletion.CASCADE, to='core.estadoambiental')),
                ('id_tipo_variable', models.ForeignKey(db_column='id_tipo_variable', on_delete=django.db.models.deletion.CASCADE, to='core.tipovariable')),
            ],
            options={
                'db_table': 'umbral_alerta',
            },
        ),
        migrations.AddField(
            model_name='alerta',
            name='id_umbral',
            field=models.ForeignKey(db_column='id_umbral', on_delete=django.db.models.deletion.CASCADE, to='core.umbralalerta'),
        ),
        migrations.CreateModel(
            name='AuditoriaSistema',
            fields=[
                ('id_auditoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('tabla_afectada', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuario')),
            ],
            options={
                'db_table': 'auditoria_sistema',
            },
        ),
        migrations.AddField(
            model_name='dispositivoiot',
            name='id_zona',
            field=models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.CASCADE, to='core.zonamonitoreo'),
        ),
        migrations.CreateModel(
            name='RecursoHasRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso_idrecursos', models.ForeignKey(db_column='recurso_idrecursos', on_delete=django.db.models.deletion.CASCADE, to='core.recurso')),
                ('rol_idrol', models.ForeignKey(db_column='rol_idrol', on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
            ],
            options={
                'db_table': 'recurso_has_rol',
                'unique_together': {('recurso_idrecursos', 'rol_idrol')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioHasRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_idrol', models.ForeignKey(db_column='rol_idrol', on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
                ('usuario_idusuarios', models.ForeignKey(db_column='usuario_idusuarios', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_has_rol',
                'unique_together': {('usuario_idusuarios', 'rol_idrol')},
            },
        ),
    ]
